### ISSUE TITLE
Separate javascript from html

### ISSUE THREAD

**Issue by glubsy** [hydrastro/livestream#1]
Having the javascript script inlined in the html file is not ideal right now. It might be a good idea to have two separate files and load the script from the html instead of having it embedded. 

As it stands right now, it's very difficult to read and fix the javascript script.

**Comment by hydrastro** [comment]
That's right, having it in a separated script would be better, also because it's probably this script: https://github.com/video-dev/hls.js (I need to ask ottersarecool who handled the javascript part).

So, I'm pushing an update right now in order to fix this and make the whole thing more neat.
The main goal would be to stream mp4/webm in order to get rid of the js code, but as now we have to keep it.
If you have any other suggestions, you're welcome!
